# Generated by Django 4.0.4 on 2022-05-06 15:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
